//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LopushokApp.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public string productArcticle { get; set; }
        public Nullable<int> productTypeId { get; set; }
        public string name { get; set; }
        public Nullable<int> minPriceForAgent { get; set; }
        public string picture { get; set; }
        public Nullable<int> quantityPeopleForManufacture { get; set; }
        public Nullable<int> numberOfManufacture { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
